// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUSbIMj-xwK6JProeRKkxLichbfQ4gjZs',
    appId: '1:382440265351:web:9eec7bc9e802a1536f8a22',
    messagingSenderId: '382440265351',
    projectId: 'education-app-8e1f6',
    authDomain: 'education-app-8e1f6.firebaseapp.com',
    storageBucket: 'education-app-8e1f6.appspot.com',
    measurementId: 'G-M6FDHXC0S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF0OVInzBbX4KhTraiz2s_Tnma-BeIbwc',
    appId: '1:382440265351:android:cf0203f143ad0e1c6f8a22',
    messagingSenderId: '382440265351',
    projectId: 'education-app-8e1f6',
    storageBucket: 'education-app-8e1f6.appspot.com',
  );
}
